@WorkOrderManagement.Api_HostAddress = http://localhost:5094

GET {{WorkOrderManagement.Api_HostAddress}}/api/workorders

###

GET {{WorkOrderManagement.Api_HostAddress}}/api/workorders/1

###

POST {{WorkOrderManagement.Api_HostAddress}}/api/workorders
Content-Type: application/json
{
  "title": "Test invalid asset",
  "description": "Testing validation",
  "status": "Open",
  "priority": "Low",
  "assetId": 1,
  "technicianId": null
}

###

DELETE {{WorkOrderManagement.Api_HostAddress}}/api/workorders/2

###

PUT {{WorkOrderManagement.Api_HostAddress}}/api/workorders/1
Content-Type: application/json
{
  "title": "Car oil change",
  "description": "Honda needs an oil change.",
  "status": "Open",
  "priority": "Medium",
  "assetId": 1,
  "technicianId": null
}

