@WorkOrderManagement.Api_HostAddress = http://localhost:5094

GET {{WorkOrderManagement.Api_HostAddress}}/api/workorders

###

GET {{WorkOrderManagement.Api_HostAddress}}/api/workorders/2

###

POST {{WorkOrderManagement.Api_HostAddress}}/api/workorders
Content-Type: application/json

{
  "title": "Replace hydraulic hose",
  "description": "Leak detected near pump.",
  "status": "Open",
  "priority": "High"
}

###

DELETE {{WorkOrderManagement.Api_HostAddress}}/api/workorders/2
